import { roboto } from "../libs/fonts";
import "./globals.css";




export const metadata = {
  title: "Recovity",
  description: "Generated by Next Js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}  `}
      >
        {children}
      </body>
    </html>
  );
}
